name: ID10T Errors
description: A CTF team
paginate: 10
domain: ctftoolkit.com
#markdown: redcarpet
kramdown:
  input: GFM
gems:
  - jekyll-paginate
#  - redcarpet
#This should revert jekyll back to kramdown, and tell it to use GitHub Flavored Markdown
